project:
  type: website
  resources:
    - urbanform/**

website:
  title: ""
  navbar:
    logo: urbanform/rkglogo_red.png
    left:
      - href: index.qmd
        text: Home
      - href: urbanform.qmd
        text: Urban Form Map
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



